version: '3.7'

services:  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: securitize-backend
    command: >
      bash -c "
      npm install 
      && npm run build 
      && cp ./.env ./dist/ 
      && node ./dist/main.js"
    ports:
    - "3001:3001"
    tty: true
    depends_on:
      - mongo
    links:
      - mongo:mongo
    container_name: securitize-backend
    networks:
      - securitize-bridge


  mongo:
    image: mongo:5.0.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo/data:/data/db
    container_name: securitize-mongo
    networks:
      - securitize-bridge

networks:
  securitize-bridge: 
    driver: bridge

